DROP DATABASE IF EXISTS pdf_analytics;
CREATE DATABASE pdf_analytics CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
USE pdf_analytics;

DROP TABLE IF EXISTS pdfa_pdf_files;
CREATE TABLE pdfa_pdf_files
(
	pdf_id	BIGINT	UNSIGNED NOT NULL AUTO_INCREMENT	COMMENT'PK: PDF_ID',
	pdf_title	VARCHAR(150)	NOT NULL	COMMENT'PDF FILE TITLE',
	pdf_filename	VARCHAR(255)	NOT NULL	COMMENT'PDF FILE NAME',
	pdf_size	BIGINT	UNSIGNED NOT NULL DEFAULT 0	COMMENT'PDF FILE SIZE IN BYTES',
	pdf_upload_by	BIGINT	UNSIGNED NULL	COMMENT'PDF FILE UPLOADED BY USER ID',
	pdf_created	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP()	COMMENT'CREATED DATE',
	pdf_modified	DATETIME	NULL	COMMENT'MODIFIED DATE',
	pdf_status	TINYINT	NOT NULL DEFAULT 1	COMMENT'0- InActive,1- Active,2- Deleted',
    PRIMARY KEY(pdf_id),
    INDEX IDX_PDF_UPLOAD_BY(pdf_upload_by),
    INDEX IDX_PDF_STATUS(pdf_status)
)ENGINE=InnoDB COMMENT='TABLE TO STORE THE PDF FILES';

DROP TABLE IF EXISTS pdfa_pdf_sessions;
CREATE TABLE pdfa_pdf_sessions
(
	pdfs_id	BIGINT	UNSIGNED NOT NULL AUTO_INCREMENT	COMMENT'PK: PK_PDFS_ID',
	pdfs_session_id	VARCHAR(64)	NOT NULL	COMMENT'SESSION ID',
	pdfs_pdf_id	BIGINT	UNSIGNED NOT NULL 	COMMENT'FK: FK_PDFS_PDF_ID REFER PDFA_PDF_FILES(PDF_ID)',
	pdfs_user_ip	VARCHAR(45)	NULL	COMMENT'USER IP ADDRESS',
	pdfs_user_agent	TEXT	NULL	COMMENT'USER AGENT DETAILS',
	pdfs_started_at	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP()	COMMENT'SESSION STARTED',
	pdfs_started	DATE	GENERATED ALWAYS AS (DATE(pdfs_started_at)) STORED COMMENT'STORED	SESSION STARTED DATE ONLY STORED',
	pdfs_ended_at	DATETIME	NULL	COMMENT'SESSION ENDED',
	pdfs_is_active	TINYINT	NOT NULL DEFAULT 1	COMMENT'0- InActive,1- Active',
    PRIMARY KEY(pdfs_id),
    CONSTRAINT FK_PDFS_PDF_ID FOREIGN KEY(pdfs_pdf_id) REFERENCES pdfa_pdf_files(pdf_id),
    UNIQUE INDEX UDX_PDFS_SESSION_ID(pdfs_session_id),
    INDEX IDX_PDFS_ISACTIVE(pdfs_is_active)
)ENGINE=InnoDB COMMENT='TABLE TO STORE THE PDF SESSIONS';

DROP TABLE IF EXISTS pdfa_pdf_page_views;
CREATE TABLE pdfa_pdf_page_views
(
	pgvw_id	BIGINT	UNSIGNED NOT NULL AUTO_INCREMENT	COMMENT'PK: PK_PGVW_ID',
	pgvw_pdf_id	BIGINT	UNSIGNED NOT NULL 	COMMENT'FK: FK_PGVW_PDF_ID REFER PDFA_PDF_FILES(PDF_ID)',
	pgvw_pdfs_id	BIGINT	UNSIGNED NOT NULL 	COMMENT'FK: FK_PGVW_PDFS_ID REFER PDFA_PDF_SESSIONS(PDFS_ID)',
	pgvw_page_no	INTEGER	NOT NULL	COMMENT'PDF FILE PAGE NUMBER',
	pgvw_viewed_at	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP()	COMMENT'PDF DOCUMENT VIEW DATE WITH TIME',
	pgvw_viewed	DATE	GENERATED ALWAYS AS (DATE(pgvw_viewed_at))  STORED	COMMENT'PDF DOCUMENT VIEWED DATE ONLY STORED',
	PRIMARY KEY(pgvw_id),
	CONSTRAINT FK_PGVW_PDF_ID FOREIGN KEY(pgvw_pdf_id) REFERENCES pdfa_pdf_files(pdf_id),
	CONSTRAINT FK_PGVW_PDFS_ID FOREIGN KEY(pgvw_pdfs_id) REFERENCES pdfa_pdf_sessions(pdfs_id)
)ENGINE=InnoDB COMMENT='TABLE TO STORE THE PDF FILE PAGE VIEWS';

DROP TABLE IF EXISTS pdfa_pdf_page_daily_stats;
CREATE TABLE pdfa_pdf_page_daily_stats
(
	pdst_id	BIGINT	UNSIGNED NOT NULL AUTO_INCREMENT	COMMENT'PK: PK_PDST_ID',
	pdst_pdf_id	BIGINT	UNSIGNED NOT NULL 	COMMENT'FK: FK_PDST_PDF_ID REFER PDFA_PDF_FILES(PDF_ID)',
	pdst_pdf_page_no	INTEGER	NOT NULL	COMMENT'PDF FILE PAGE NUMBER',
	pdst_viewed_date	DATE	NOT NULL	COMMENT'PDF FILE VIEWED DATE',
	pdst_total_views	INTEGER	NOT NULL DEFAULT 0	COMMENT'TOTAL VIEWS',
    PRIMARY KEY(pdst_id),
    CONSTRAINT FK_PDST_PDF_ID FOREIGN KEY(pdst_pdf_id) REFERENCES pdfa_pdf_files(pdf_id),
    UNIQUE INDEX UDX_PDF_PAGE_VIEW(pdst_pdf_id,pdst_pdf_page_no,pdst_viewed_date)
)ENGINE=InnoDB COMMENT='TABLE TO STORE THE AGGREGATE VALUES OF PDF FILE DAILY STATS';

DROP TABLE IF EXISTS db_script_version;
CREATE TABLE db_script_version
(
	dbsv_id	INTEGER	PRIMARY KEY AUTO_INCREMENT NOT NULL	COMMENT'PRIMARY KEY',
	dbsv_name	VARCHAR(255)	NOT NULL	COMMENT'Script Version Name',
	dbsv_date	DATETIME	NOT NULL  DEFAULT CURRENT_TIMESTAMP()	COMMENT'Script Date'
)ENGINE=InnoDB COMMENT='TABLE TO STORE THE DB VERSIONS / PATCHES EXECUTED DETAILS';

-- Additional Suggestions for adding Index - Experts View
ALTER TABLE pdfa_pdf_page_views 
ADD INDEX IDX_PDF_DATE (pgvw_pdf_id, pgvw_viewed),
ADD INDEX IDX_PDF_PAGE (pgvw_pdf_id, pgvw_page_no);

ALTER TABLE pdfa_pdf_sessions
ADD INDEX IDX_PDF_ID (pdfs_pdf_id);